name: codacy-coverage-reporter

on:
  pull_request:
    branches: [ master ]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Repository
        run: |
            npm install
            npm test
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/clover.xml
